services:
  - type: web
    name: prepshark-api
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: prepshark-db
          property: connectionString

databases:
  - name: prepshark-db
    databaseName: prepshark
    user: prepshark
    region: singapore
    plan: free
